#!/bin/sh

# File name is calibre_web
# Place this file into /etc/rc.d
# Edit /etc/rc.conf to include calibre_web_enable=YES
# Edit /etc/rc.conf to change default service configuration

# PROVIDE: calibre_web
# BEFORE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin"

name=calibre_web
rcvar=calibre_web_enable

load_rc_config $name

: ${calibre_web_enable:=NO}
: ${calibre_web_user:=calibreweb}
: ${calibre_web_dbpath:=/usr/local/etc/calibre-web}
: ${calibre_web_logfile:=/var/log/calibre-web/calibre-web.log}

pidfile="/var/run/${name}/${name}.pid"

#shebang error?
command="env CALIBRE_DBPATH=${calibre_web_dbpath} python3 /usr/local/app/calibre-web/cps.py"
#command_args ???
#required_dirs="${calibre_web_dbpath}"

#calibre_web_home=${calibre_home:-$(getent passwd ${calibre_web_user} | awk -F: '{print $6}')}
#calibre_web_env="${calibre_web_env} CALIBRE_DBPATH=${calibre_web_dbpath}"

start_precmd="${name}_prestart"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

calibre_web_prestart()
{
	install -d -o ${calibre_web_user} -m 755 /var/run/${name}
	install -d -o ${calibre_web_user} -m 755 ${calibre_web_dbpath}
    install -d -o ${calibre_web_user} -m 755 `dirname ${calibre_web_logfile}`
}

calibre_web_start()
{
    if [ -e ${pidfile} ];
    then
        echo "${name} is already running"
    else
        echo "Starting ${name}"
        /usr/sbin/daemon -u ${calibre_web_user} -p ${pidfile} ${command}
    fi
}

calibre_web_stop()
{
    if [ -e ${pidfile} ];
    then
        echo "Stopping ${name}"
        kill `cat ${pidfile}`;
        sleep 1
    else
        echo "${name} is not running"
    fi
}

run_rc_command "$1"
